### ISSUE TITLE
feature: support for basic strategies

### ISSUE THREAD

**Issue by lucasmenendez** [vocdoni/census3#75]
***[WIP]***

This issue describes how the strategies must work.

A strategy is a definition of a group of previously created tokens and how their scanned holders must be combined to create a census.
* Must support **combinations of tokens** which contains:
  * A **operator**, which is a function associated with a tag (e.g. `AND`) that are used to combine token holders.
  * Two **token symbols** (e.g. `'BTC'`), that refer to the token holders.
  * Must have the following format: `<token_symbol> <operator> <token_symbol>`, e.g. `BTC OR ETH`.
  * If any token symbol contains reserved characters (spaces or parenthesis), they must be prefixed with double slash to scape them. E.g. `USD Coin` ==> `USD\\ Coin`
* Must support **groups** of combinations, e.g. `USDC AND (ETH OR (BTC AND DAI))`

### TODO
- [x] #86 
- [x] Integrate the lexer PoC.
- [x] Define and implement operators and min balance reducer.
- [x] API endpoint to parsing a validating predicates (POST `/strategies/predicate/parse`). Check if we can estimate the number of holders of a predicate.
- [x] Modify database table `strategy_tokens` to remove `method_hash` column.
- [x] API endpoint to create a new strategy (POST `/strategies`).
  - Request:
  ```json
  {
    "name": "test strategy",
    "predicate": "USDC AND (ETH OR (BTC AND DAI))",
    "minBalances": {
       "USDC": "120000000000000000000000",
       "ETH": "320000000000000000000000"
    }
  }
  ```
  - Must check the name availability.
  - Must validate the predicate and check the tokens.
  - Must create the strategy on the database.
- [x] Refactor other API endpoints regarding strategies:
  - [x] GET `/strategies`
  - [x] GET `/strategies/{strategy_id}`
  - [x] GET `/strategies/token/{token_id}`
  - [x] GET `/censuses/strategy/{strategy_id}`
- [x] Update `api/README.md` with new endpoints documentation.
- [x] New API endpoint to retrieve the supported strategy predicate operators.
